dist: xenial

services:
  - docker

language: python
python:
  - '3.7'

cache: pip

env:
  HOST_PORT: 8000

before_install:
  - docker-compose build

script:
  - docker-compose run --rm --entrypoint "" app pytest
