version: '3'
services:
  db:
    container_name: aplans-db
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

  app:
    container_name: aplans
    build: .
    restart: always
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://db/aplans
    ports:
      - "${HOST_PORT}:8000"
    depends_on:
      - db

volumes:
  db_data:
